server:
  port: "${SERVER_PORT}"
spring:
  application:
    name: "BusinessManagerCore"
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,https://tavo826.github.io/,https://businessmanagement.store"
security:
  jwt:
    secret: "${JWT_SECRET}"
    expiration: "${JWT_EXPIRATION}"
  webhook-token: "${WEBHOOK_TOKEN}"
adapters:
  r2dbc:
    host: "${CORE_DB_HOST}"
    port: "${CORE_DB_PORT}"
    database: "${CORE_DB_NAME}"
    schema: "${CORE_DB_SCHEMA}"
    username: "${CORE_DB_USERNAME}"
    password: "${CORE_DB_PASSWORD}"
    pool:
      initial-size: "${CORE_DB_POOL_INITIAL_SIZE}"
      max-size: "${CORE_DB_POOL_MAX_SIZE}"
      max-idle-time: "${CORE_DB_POOL_MAX_IDLE_TIME}"
  restmessageconsumer:
    timeout: 5000
    url: "${URI_USER_MESSAGE}"
    token: "${REST_USER_TOKEN}"
  reststockconsumer:
    timeout: 5000
    url: "${URI_STOCK_SERVICE}"
  restinventoryconsumer:
    timeout: 10000
    url: "${URI_INVENTORY_SERVICE}"
  gemini:
    api-key: "${GEMINI_API_KEY}"
    memory-size: "${GEMINI_MEMORY_SIZE}"
    model-name: "${GEMINI_MODEL:gemini-2.0-flash}"
    temperature: "${GEMINI_TEMPERATURE:0.7}"
logging:
  level:
    io:
      r2dbc:
        postgresql: "${LOGGING_LEVEL}"
    org:
      springframework:
        data:
          r2dbc: "${LOGGING_LEVEL}"

resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
